### ISSUE TITLE
Weight vector is normalized after call with normalize = TRUE

### ISSUE THREAD

**Issue by guenter-hitsch** [kevinushey/RcppRoll#20] opened 2017-01-19 02:10 UTC
First, thanks for making RcppRoll available! It's very helpful for a new data science class that I'm teaching, especially because I can't expect my students to code Rcpp snippets.

Here's a little bug that I ran into. The `normalize = TRUE` flag will result in `w` itself being normalized. I can easily avoid this with `weights = copy(w)` but nonetheless I doubt this is the intended behavior.

Example:
```r
x = 1:6
w = c(0.5, 0.5, 1.0)
roll_sum(x, n = 3L, weights = w, normalize = TRUE, align = "right",  fill = NA)
```
The result is that 
```
> w
[1] 0.75 0.75 1.50
```

**Comment by kevinushey** [comment] 2017-05-03 17:59
Thanks! You're indeed right that this is not the intended behavior; I should make sure that the weights vector is duplicated before using it on the C++ side.

**Comment by kevinushey** [comment] 2018-06-04 15:04
This should be fixed in dev -- will be planning to submit to CRAN soon-ish.

**Closed by kevinushey** 2018-06-04 15:04 UTC
